"""empty message

Revision ID: 1b490306b072
Revises: 
Create Date: 2020-01-28 14:24:13.316981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b490306b072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_timestamp'), 'file', ['timestamp'], unique=False)
    op.create_table('access',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('file_id', 'client_id')
    )
    op.create_table('contract_recv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_recv_client_id'), 'contract_recv', ['client_id'], unique=False)
    op.create_index(op.f('ix_contract_recv_file_id'), 'contract_recv', ['file_id'], unique=False)
    op.create_table('contract_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_sent_file_id'), 'contract_sent', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_sent_file_id'), table_name='contract_sent')
    op.drop_table('contract_sent')
    op.drop_index(op.f('ix_contract_recv_file_id'), table_name='contract_recv')
    op.drop_index(op.f('ix_contract_recv_client_id'), table_name='contract_recv')
    op.drop_table('contract_recv')
    op.drop_table('access')
    op.drop_index(op.f('ix_file_timestamp'), table_name='file')
    op.drop_table('file')
    op.drop_table('client')
    # ### end Alembic commands ###
